"""add_fire_intelligence_and_operator_decision

Revision ID: 01028568b3a2
Revises: 
Create Date: 2026-07-08 23:29:54.335081
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01028568b3a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('severity', sa.String(length=20), nullable=True))
    op.add_column('incidents', sa.Column('estimated_cause', sa.String(length=100), nullable=True))
    op.add_column('incidents', sa.Column('observed_behaviour', sa.String(length=100), nullable=True))
    op.add_column('incidents', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('incidents', sa.Column('recommended_actions', sa.Text(), nullable=True))
    op.add_column('incidents', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('incidents', sa.Column('operator_decision', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'operator_decision')
    op.drop_column('incidents', 'explanation')
    op.drop_column('incidents', 'recommended_actions')
    op.drop_column('incidents', 'ai_summary')
    op.drop_column('incidents', 'observed_behaviour')
    op.drop_column('incidents', 'estimated_cause')
    op.drop_column('incidents', 'severity')
    # ### end Alembic commands ###
